### ISSUE TITLE
Groovy syntax of packForXcode

### ISSUE THREAD

**Issue by rhonyabdullah** [kotlin-hands-on/mpp-ios-android#10]
I found hard converting this kotlin dsl into groovy syntax, anybody has groovy syntax version ? Because i need that [packForXcode](https://github.com/kotlin-hands-on/mpp-ios-android/blob/8cfc677610d2d469b6201155a5d5d513a46d6e89/SharedCode/build.gradle.kts#L35) task.

**Comment by artdfel** [comment]
Hi! You can find it in the old repository of this example, it has Groovy-only scripts. Here is the packForXcode [part](https://github.com/Kotlin/kotlin-examples/blob/master/tutorials/mpp-iOS-Android/SharedCode/build.gradle).
